# 19-3-2024


In [12]:
# numpy = numerical python
# use : sciencetific computing
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
arr = np.zeros((2,3))
print(arr)
arr = np.ones((2,3))
print(arr)


[1 2 3 4 5]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [67]:
# Create array with 4x5 with 20 random 2 digit number
arr =  np.random.randint(10,100,20)
arr2 = arr.reshape(4,5)

# if isinstance(arr, np.ndarray):       # To check numpy arr or not
#     print('true')
print(arr2)

[[68 36 32 31 80]
 [19 14 51 48 90]
 [42 98 96 90 91]
 [81 32 54 30 48]]


In [41]:
# to check the demension of array (1d, 2d or nd)
arr.ndim

1

In [55]:
print(arr)
arr[-2::]

[85 93 38 88 70 41 99 24 72 14 90 31 87 31 11 72 82 11 17 68]


array([17, 68])

In [56]:
arr[0]

85

In [57]:
arr[2]

38

In [59]:
arr[:3]

array([85, 93, 38])

In [61]:
arr2

array([[85, 93, 38, 88, 70],
       [41, 99, 24, 72, 14],
       [90, 31, 87, 31, 11],
       [72, 82, 11, 17, 68]])

In [60]:
arr2[1:3, 0:2]

array([[41, 99],
       [90, 31]])

In [63]:
# arr2[1, 3] and arr[1][3]      # Same
arr2[0:2]

array([[85, 93, 38, 88, 70],
       [41, 99, 24, 72, 14]])

In [69]:
# Numpy array allow broadcasting
arr2[1:3] = 2
arr2

array([[68, 36, 32, 31, 80],
       [ 2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2],
       [ 2,  2,  2,  2,  2]])

In [71]:
# Numpy array allow victorization

In [82]:
arr < 50


array([False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [84]:
arr[arr < 50]


array([36, 32, 31,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2])

In [85]:
arr[arr > 20]

array([68, 36, 32, 31, 80])

In [86]:
arr[(arr > 20) & (arr < 50)]

array([36, 32, 31])

In [88]:
arr2[(arr2 <= 0) | (arr2 >= 79)]


array([80])

In [91]:
a = np.array([
    [1,2,3,4,5],
    [11,12,13,14,15],
    [21,22,23,24,25]

])
a

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

In [93]:
a.sum()

195

In [97]:
a.sum(axis=1)


array([ 15,  65, 115])

In [99]:
a.min()

1

In [100]:
a.max()

25

In [98]:
a.mean()

13.0