### Questions

In [1]:
# 1. Import the package numpy as np
import numpy as np

In [2]:
# 2. Create 1D array "a1" from the list and display the properties
a = np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
# 3. Create 2D array "a2" of one digit random numbers with shape (4, 5) and display the properties
a = np.random.randint(10,100,20)
a2 = a.reshape(4,5)
a2

array([[89, 76, 60, 53, 77],
       [93, 66, 85, 17, 45],
       [98, 91, 56, 13, 71],
       [97, 34, 52, 63, 11]])

In [7]:
# 4. Get only first row from a2
a2[0]

array([89, 76, 60, 53, 77])

In [10]:
# 5. Get only last column from a2
a2[::,4]

array([77, 45, 71, 11])

In [11]:
# 6. Get the value at position 2, 4
a2[2,4]

71

In [12]:
# 7. Get the data from first two rows and last three columns. Hint : [ start : end : step ]
a2[0:2, 2:5]

array([[60, 53, 77],
       [85, 17, 45]])

In [40]:
a2

array([[89, 76, 60, 53, 77],
       [93, 66, 85, 17, 45],
       [98, 91, 56, 13, 71],
       [97, 34, 52, 63, 11]])

In [41]:
# 8. Add number 100 to elements in array a2

a2 + 100


####################################

array([[189, 176, 160, 153, 177],
       [193, 166, 185, 117, 145],
       [198, 191, 156, 113, 171],
       [197, 134, 152, 163, 111]])

In [18]:
# 9. get the values which are greatet than the overall average
m = a.mean()
print('Mean: ',m)
a[a > m]
a

Mean:  62.35


array([89, 76, 60, 53, 77, 93, 66, 85, 17, 45, 98, 91, 56, 13, 71, 97, 34,
       52, 63, 11])

In [26]:
# 10. Create a numpy array a3 with 20 equidistant elements in range 1, 5

In [35]:
# 11. Create (3, 5) ndarray with numbers starting 11 till 25 (numbers should not repeat) & save in a4
n = []
j=11
for i in range(0,15):
    n.append(j)
    j+=1
a4 = np.array(n)
a4 = a4.reshape(3,5)
a4

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# 12. Get the values from a4 which are less than 15 and greater than 20
a4[(a4 < 15) & (a4 > 20)]

array([], dtype=int32)